pipeline {
    agent any
    tools {
        jdk 'Java17'
        maven 'Maven3'
    }
    stages {
        stage('Compile') {
            steps {
                // Is block ke andar jo bhi likhoge wo Quick folder mein chalega
                dir('Quick') {
                    sh 'mvn clean compile'
                }
            }
        }
        stage('Package') {
            steps {
                dir('Quick') {
                    sh 'mvn package -DskipTests'
                }
            }
        }
    }
}



// pipeline {
//     agent any
//     tools {
//         jdk 'Java17'
//         maven 'Maven3'
//     }
//     stages {
//         stage('Compile') {
//             steps {
//                 // 'dir' command ka use karke hum Jenkins ko 'Quick' folder ke andar bhej rahe hain
//                 dir('Quick') {
//                     sh 'mvn clean compile'
//                 }
//             }
//         }
//         stage('Package') {
//             steps {
//                 dir('Quick') {
//                     sh 'mvn package -DskipTests'
//                 }
//             }
//         }
//     }
// }
